baseurl = "http://ali88code.github.io/"
languageCode = "en-us"
title = "My Name is ali88.It is my Hugo Host First."
theme = "crisp"
author = "Ali88 Cheng"
publishdir="/var/www/html/ali88code.github.io"
